version: '3.8'

services:
  langgraph-redis:
    image: mariox1105/langgraph-redis:6
    container_name: langgraph-redis
    restart: unless-stopped
    networks:
      - langgraph_network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 1s
      retries: 5

  langgraph-postgres:
    image: mariox1105/langgraph-pgvector:pg16
    container_name: langgraph-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    networks:
      - langgraph_network
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "shared_preload_libraries=vector"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 60s
      timeout: 1s
      start_period: 10s
      retries: 5

  langgraph-api:
    image: mariox1105/langgraph-api:latest
    container_name: langgraph-api
    restart: unless-stopped
    ports:
      - "8123:8000"
    networks:
      - langgraph_network
    volumes:
      - budget_data:/deps/ai_sql_generator_langgraph/data
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      LANGSMITH_API_KEY: ${LANGSMITH_API_KEY}
      REDIS_URI: redis://langgraph-redis:6379
      POSTGRES_URI: postgres://postgres:postgres@langgraph-postgres:5432/postgres?sslmode=disable
      LANGSMITH_PROJECT: ai-sql_generator_langgraph
      PYTHONFAULTHANDLER: 1
      PYTHONUNBUFFERED: "True"
      PORT: 8000
      N_WORKERS: 1
      N_JOBS_PER_WORKER: 10
      LANGGRAPH_SERVER_HOST: 0.0.0.0
      PYTHONPATH: "/deps/ai_sql_generator_langgraph/src:"
      LANGSERVE_GRAPHS: '{"agent": "/deps/ai_sql_generator_langgraph/src/react_agent/graph.py:graph"}'
    depends_on:
      - langgraph-redis
      - langgraph-postgres
    healthcheck:
      test: ["CMD-SHELL", "python /api/healthcheck.py"]
      interval: 60s
      timeout: 2s
      start_period: 10s
      retries: 5

networks:
  langgraph_network:
    driver: bridge

volumes:
  redis_data:
  postgres_data:
  budget_data:
    external: true